services:
  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: ECOMMERCE
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./ecommerce_dump_data.sql:/docker-entrypoint-initdb.d/ecommerce_dump_data.sql
    networks:
      - ecommerce-app-network
  
  ecommerce-service:
    build:
      context: ./ecommercebackend
      dockerfile: Dockerfile
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    networks:
      - ecommerce-app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://34.171.224.151:3306/ECOMMERCE
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: my-secret-pw
  
  ecommerce-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - ecommerce-app-network

volumes:
  mysql-data:
    driver: local

networks:
  ecommerce-app-network:
    driver: bridge
